---
- name: restart ntp
  service:
    name: "{{ ntp_daemon }}"
    state: restarted
  when: ntp_enabled

- name: restart cron
  service:
    name: "{{ ntp_cron_daemon }}"
    state: restarted
  when:
    - ntp_cron_daemon | length > 0
    - ansible_facts.services[ntp_cron_daemon] is defined
    - ansible_facts.services[ntp_cron_daemon].state == 'running'
