---
- name: Restart ntp
  ansible.builtin.service:
    name: "{{ ntp_daemon }}"
    state: restarted
  when: ntp_enabled | bool

- name: Restart cron
  ansible.builtin.service:
    name: "{{ ntp_cron_daemon }}"
    state: restarted
  when: ntp_cron_handler_enabled | bool
