---
- name: Converge
  hosts: all
  become: true

  vars:
    ntp_enabled: false
    ntp_manage_config: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.ntp
